export const enum CustomerActions {
  initCustomerState = 'Init Customer State',
  resetCustomerState = 'Reset Customer State',
  setCustomer = 'Set Customer ',
  clearErrorMessage = 'Clear Error Message',
  loginCustomer = 'Login Customer',
  loginCustomerSucces = 'Login Customer Success',
  loginCustomerFailure = 'Login Customer Failure',
  loginCustomerSuccsess = 'Login Customer Succsess',
  reloginCustomer = 'Relogin Customer',
  reloginCustomerFailure = 'Relogin Customer Failure',
  reloginCustomerSuccsess = 'Relogin Customer Succsess',
  refreshCustomer = 'Refresh Customer',
  refreshCustomerFailure = 'Refresh Customer Failure',
  refreshCustomerSuccsess = 'Refresh Customer Succsess',
  registerCustomer = 'Register Customer',
  registerCustomerFailure = 'Register Customer Failure',
  registerCustomerSuccsess = 'Register Customer Succsess',
  logoutCustomer = 'Logout Customer',
  loadAnonymousCustomer = 'Load Anonymous Customer',
  loadAnonymousCustomerFailure = 'Load Anonymous Customer Failure',
  loadAnonymousCustomerSuccsess = 'Load Anonymous Customer Success',
  changePassword = 'Change Password Customer',
  changePasswordFailure = 'Change Password Customer Failure',
  changePasswordSuccsess = 'Change Password Customer Success',
}
